FROM node:8-alpine

WORKDIR /usr/src/frontend

RUN \
  apk add --no-cache python make g++ && \
  apk add vips-dev fftw-dev --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/community --repository http://dl-3.alpinelinux.org/alpine/edge/main && \
  rm -fR /var/cache/apk/*

RUN npm install -g gatsby-cli yarn

COPY package.json /usr/src/frontend

RUN yarn install && yarn cache clean

COPY . /usr/src/frontend

CMD ["yarn", "develop", "-H", "0.0.0.0" ]