version: "3"

services:
  server:
    build:
      context: ../.
      dockerfile: docker/nginx/Dockerfile.dev
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - frontend:frontend
      - backend:backend
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    command: gatsby develop -H 0.0.0.0 -p 1234
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
      - GATSBY_TELEMETRY_DISABLED=1
    volumes:
      - ./../frontend:/usr/src/frontend
    ports:
      - "1234:1234"
    depends_on:
      - "backend"
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    env_file: ../backend/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./../backend:/usr/src/backend
    ports:
      - "3000:3000"
    links:
      - redis
    depends_on:
      - db_mongo
      - redis
  db_mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
